### ISSUE TITLE
All points are imported but not faces, please help!

### ISSUE THREAD

**Issue by roycramer** [sugiany/blender_mmd_tools#35]
I tried importing models from here:
http://naruchan101.deviantart.com/art/MMDxRWBY-RWBY-Volume-1-Pack-DL-491669276
using the latest version of blender.

I don't seem to get any errors but only the points are imported, whereas the flat faces do not appear.
Are the models just bad or is there something I'm doing wrong?

**Comment by sugiany** [comment]
The PMX model files contain the texture path to an image file that does not exist.

Basically, I believe the model should be modified for this problem,　but I think that the current behavior of mmd_tools is not good. Therefore, I fixed mmd_tools to import such files.
mmd_tools of the master branch can import these pmx files now.

**Comment by roycramer** [comment]
Thank you so much for your quick response!
