### ISSUE TITLE
Import fails not finding bone

### ISSUE THREAD

**Issue by darkf** [sugiany/blender_mmd_tools#40]
When trying to import a model:

	  File "C:\Program Files\Blender Foundation\Blender\2.74\scripts\addons\mmd_tools\core\pmx\importer.py", line 195, in __sortPoseBonesByBoneIndex
	    r.append(pose_bones[i])
	KeyError: 'bpy_prop_collection[key]: key "右瞳" not found'

Full log here: https://gist.github.com/darkf/eec0c9c2816941e0a129

**Comment by sugiany** [comment]
Thank you for your report.
Your error was caused by a bug in mmd_tools. It has been fixed in the current master branch.
