### ISSUE TITLE
Where can I know how the mmd file format is defined

### ISSUE THREAD

**Issue by threethreenine** [sugiany/blender_mmd_tools#72]
I want to add mmd extension on other engines，i need to know the file farmat of mmd.
For example, the vertex storage arrangement in the PMX model, bone binding relationship, expression and expression drive, bone animation in vmd, and the arrangement of key frames of expression animation.
Now I come across a .pmx format model, I can open it with MikuMIkuDance, but not with the PMXEditor.exe tool. When I parse this .pmx file, data out of bounds occurs at the extended Morph location, I don’t know if I parse The problem with the algorithm is also the problem with the model itself.

**Comment by yanagiragi** [comment]
You may check [this](https://gist.github.com/felixjones/f8a06bd48f9da9a4539f)

**Comment by threethreenine** [comment]
@yanagiragi  thank you !
